OPENAI_API_KEY="sk-"
TOGETHER_API_KEY="9a8d7bb7e82874baa4e6fba27cc32e07be2fe97ac2a53be0bda5b6fb1201ace4"
TOGETHER_BASE_URL="https://api.together.xyz"
ANYSCALE_API_KEY=""
ANYSCALE_BASE_URL="https://api.endpoints.anyscale.com/v1"
